import {client} from '@/lib/contentful'
import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import ContentBlock from "@/components/ContentBlock"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home({nexxxt}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          {nexxxt.map((next, i) => (
            <ContentBlock key={next.fields.slug || i} nexxxt={next} />
          ))}
        </main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const response = await client.getEntries({ content_type: "contentBlock" });

  return {
    props: {
      nexxxt: response.items,
      revalidate: 70,
    }
  }
}
